services:
  frontend:
    # Frontend Stuff
    build:
      context: packages/frontend
      dockerfile: ./Dockerfile.dev

    volumes:
      - ./packages/frontend:/frontend

  backend:
    # Backend Stuff
    build:
      context: packages/backend
      dockerfile: ./Dockerfile.dev

    volumes:
      - ./packages/backend/src:/backend:ro

  router:
    volumes:
        - ./packages/router/Caddyfile.dev:/etc/caddy/Caddyfile
        - ./certs:/certs:ro
        - caddy_data:/data

networks:
  docker-network:
    driver: bridge
