<script lang="ts">
	import { fade } from 'svelte/transition';

	// --- Logic ---
	import type { Props } from '..';
	import { v4 as uuidv4 } from 'uuid';

	let { meowSpriteClass = $bindable('') }: Props = $props();

	const sprites: Record<string, null> = $state({});

	export function spawnSprite(ttl: number = 1000) {
		const id = uuidv4();
		console.log('Spawn Sprite', id);

		// Save self into sprites rune
		sprites[id] = null;

		// Remove self from sprites rune
		setTimeout(() => {
			delete sprites[id];
		}, ttl);
	}

	function randomPos(min: number = 10, max: number = 90): [string, string] {
		const x = `${Math.round(Math.random() * (max - min) + min)}%`;
		const y = `${Math.round(Math.random() * (max - min) + min)}%`;
		return [x, y];
	}

	function flyfade(
		node: Element,
		{ duration, start = 0, end = 0, intro = false }: { duration: number; start?: number; end?: number; intro?: boolean }
	) {
		return {
			duration,
			css: (t: number) => {
                const tt = intro ? t : 1 - t;
				const y = start + (end - start) * tt;
				return `
                  opacity: ${t};
                  transform: translate3d(0, ${y}px, 0);
                `;
			}
		};
	}
</script>

{#each Object.keys(sprites) as id (id)}
	{@const [x, y] = randomPos()}
	<div
		class={`absolute`}
		style:left={x}
		style:top={y}
		in:flyfade={{ duration: 1000, start: 10, end: 0, intro: true }}
		out:flyfade={{ duration: 1000, start: 0, end: -10 }}
	>
		{id}
	</div>
{/each}

<!--@component
    Generated by SvelteForge🔥
-->
