<script lang="ts">
	import { flyfade } from '@transitions'

	// --- Logic ---
	import type { Props } from '..';
	import { v4 as uuidv4 } from 'uuid';

	let { meowSpriteClass = $bindable('') }: Props = $props();

	const sprites: Record<string, null> = $state({});

	export function spawnSprite(ttl: number = 1000) {
		const id = uuidv4();
		console.log('Spawn Sprite', id);

		// Save self into sprites rune
		sprites[id] = null;

		// Remove self from sprites rune
		setTimeout(() => {
			delete sprites[id];
		}, ttl);
	}

	function randomPos(min: number = 10, max: number = 90): [string, string] {
		const x = `${Math.round(Math.random() * (max - min) + min)}%`;
		const y = `${Math.round(Math.random() * (max - min) + min)}%`;
		return [x, y];
	}

</script>

{#each Object.keys(sprites) as id (id)}
	{@const [x, y] = randomPos()}
	<div
		class={`absolute`}
		style:left={x}
		style:top={y}
		in:flyfade={{ duration: 1000, start: 10, end: 0, intro: true }}
		out:flyfade={{ duration: 1000, start: 0, end: -10 }}
	>
		{id}
	</div>
{/each}

<!--@component
    Generated by SvelteForge🔥
-->
