<script lang="ts">
	import { flyfade } from '@transitions'

	// --- Logic ---
	import type { Props } from '..';
	import { v4 as uuidv4 } from 'uuid';
	import { onMount } from 'svelte';
	import { randomNumber } from '@utils';

	let { meowSpriteClass = $bindable('') }: Props = $props();

	const sprites: Record<string, null> = $state({});

	let sprites_directory: Record<string, string> = $state({});
	let meows_directory: Record<string, string> = $state({});

	async function cacheImages(image_list: string[]) {
		image_list.forEach(async (image_path) => {
			const response = await fetch(`https://api.${window.location.host}/sprites/${image_path}`)
			if (response.status == 200) {
				const blob = await response.blob();
        		const objectUrl = URL.createObjectURL(blob);
				sprites_directory[image_path] = objectUrl;
			} 
		});
	}

	async function cacheMeows(meow_list: string[]) {
		meow_list.forEach(async (meow_path) => {
			const response = await fetch(`https://api.${window.location.host}/meows/${meow_path}`)
			if (response.status == 200) {
				const blob = await response.blob();
        		const objectUrl = URL.createObjectURL(blob);
				meows_directory[meow_path] = objectUrl;
			} 
		});
	}

	async function playSound(blob: string) {
		const response = await fetch(blob);
		const data = await response.arrayBuffer();
		const audioCtx = new AudioContext();
		const buffer = await audioCtx.decodeAudioData(data);
		const source = audioCtx.createBufferSource();
		source.buffer = buffer
		source.connect(audioCtx.destination);
		source.start();
	}

	function getRandomItem(obj: Record<string, any>): any {
		var keys = Object.keys(obj);
    	return obj[keys[ keys.length * Math.random() << 0]];
	}

	onMount(async () => {
		const sprites_response = await fetch(`https://api.${window.location.host}/sprites`);
		if (sprites_response.status == 200) {
			const sprites_directory_response = await sprites_response.json();
			cacheImages(sprites_directory_response)
		}

		const meows_response = await fetch(`https://api.${window.location.host}/meows`);
		if (meows_response.status == 200) {
			const meows_directory_response = await meows_response.json();
			cacheMeows(meows_directory_response);
		}
	})

	function getRandomSprite(): string {
		return getRandomItem(sprites_directory);
	}

	function getRandomMeow(): string {
		return getRandomItem(meows_directory);
	}

	

	export async function spawnSprite(ttl: number = 1000) {
		const id = uuidv4();

		// Save self into sprites rune
		sprites[id] = null;

		await playSound(getRandomMeow());

		// Remove self from sprites rune
		setTimeout(() => {
			delete sprites[id];
		}, ttl);
	}

	function randomPos(min: number = 10, max: number = 90): [string, string] {
		const x = `${Math.round(Math.random() * (max - min) + min)}%`;
		const y = `${Math.round(Math.random() * (max - min) + min)}%`;
		return [x, y];
	}

</script>

{#each Object.keys(sprites) as id (id)}
	{@const [x, y] = randomPos()}
	{@const scale = randomNumber(50, 100)}
	<div
		class={`absolute`}
		style:left={x}
		style:top={y}
		style:scale={scale/100}
		in:flyfade={{ duration: 1000, start: 10, end: 0, intro: true }}
		out:flyfade={{ duration: 1000, start: 0, end: -10 }}
	>
		<img src={getRandomSprite()} class="select-none" alt=""/>
	</div>
{/each}

<!--@component
    Generated by SvelteForge🔥
-->
